#2.3.1类型转换函数
print(bin(555))
print(oct(555))
print(hex(555))
print(float(3))
#1
num = input('请您输入数字')
print(num)
print(type(num))
print(type(int(num)))
#2
print(float('3.5'))
print(float('inf'))
print(float('-inf'))
print(complex(3,5))
print(complex(3+5j))
print(complex(8))
print(complex(8j))
#3
print(int(3.5))
print(int(-3.8))
print(int('1111'))
print(int('\t      8 \n'))
print(int('1111',8))
print(int('1111',2))
print(int('1111',16))
#4
print(ord('a'))
print(ord('蔡'))
print(list(map(ord,'董付国')))
print(str([1,2,3]))
print(type(str([1,2,3])))
#5
print(list())
print(list(range(5)))
print(tuple(range(5)))
print(dict(zip('123456','abcd')))
print(dict(name = '蔡', age = 14 , wight = 45))
print(set('Python'))
#6
print(eval('3 + 5'))
print(type(eval('3')))
print(type(eval('(1,2,3)')))
print(type(eval('[1,2,3]')))
print(type(eval('{1,2,3}')))